name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false
      chair:
        description: 'Choose chair'
        required: false
        type: choice
        options:
          - Piki
          - Ne piki
      just:
        description: 'Just do it'
        required: false
        type: boolean
      env:
        description: 'Environment'
        type: environment
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Chair: ${{ github.event.inputs.chair }}"
          echo "just: ${{ github.event.inputs.just }}"
          echo "env: ${{ github.event.inputs.env }}"
          echo "supers=${MY_SECRET:1}"
